"use client";

import { useState, useEffect, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

function SearchContent() {
  const searchParams = useSearchParams();
  const query = searchParams.get("q");
  const router = useRouter();

  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState("");

  useEffect(() => {
    if (!query) {
      setLoading(false);
      return;
    }

    const fetchKnowledge = async () => {
      setLoading(true);
      try {
        const res = await fetch("/api/ai/knowledge", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ query }),
        });
        const data = await res.json();
        if (!res.ok) {
          setResult(`Error: ${data.error || data.message || "Failed to fetch response"}`);
          return;
        }
        setResult(data.response || "No response generated.");
      } catch (error) {
        setResult(`Error connecting to AI server: ${error}`);
      } finally {
        setLoading(false);
      }
    };

    fetchKnowledge();
  }, [query]);

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <button 
        onClick={() => router.push("/knowledge")}
        className="mb-6 text-indigo-600 hover:text-indigo-800 flex items-center font-medium transition-colors"
      >
        ← Back to Knowledge Hub
      </button>

      <div className="bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden">
        <div className="bg-gradient-to-r from-indigo-700 to-purple-700 px-6 py-8 text-white relative overflow-hidden">
          {/* Decorative Background Elements */}
          <div className="absolute top-0 right-0 -mr-16 -mt-16 w-64 h-64 rounded-full bg-white opacity-10 blur-3xl"></div>
          <div className="absolute bottom-0 left-0 -ml-16 -mb-16 w-48 h-48 rounded-full bg-indigo-400 opacity-20 blur-2xl"></div>
          
          <div className="relative z-10">
            <div className="flex items-center gap-3 mb-3">
              <span className="p-2 bg-white/20 rounded-lg backdrop-blur-sm">🤖</span>
              <span className="text-indigo-100 font-medium tracking-wider uppercase text-sm">AI Clinical Analysis</span>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold mb-2">
              {query ? query.charAt(0).toUpperCase() + query.slice(1) : "Medical Query"}
            </h1>
            <p className="text-indigo-100 opacity-90 max-w-2xl text-lg">
              Comprehensive clinical breakdown generated by MedConnect AI Engine.
            </p>
          </div>
        </div>

        <div className="p-6 md:p-10">
          {loading ? (
            <div className="animate-pulse space-y-8">
              <div className="h-8 bg-gray-200 rounded w-1/3"></div>
              <div className="space-y-4">
                <div className="h-4 bg-gray-200 rounded w-full"></div>
                <div className="h-4 bg-gray-200 rounded w-full"></div>
                <div className="h-4 bg-gray-200 rounded w-5/6"></div>
              </div>
              <div className="h-8 bg-gray-200 rounded w-1/4 mt-10"></div>
              <div className="space-y-4">
                <div className="h-4 bg-gray-200 rounded w-full"></div>
                <div className="h-4 bg-gray-200 rounded w-4/5"></div>
              </div>
            </div>
          ) : result ? (
            <div className="markdown-content text-gray-800 
              [&>h1]:text-3xl [&>h1]:font-bold [&>h1]:mb-6 [&>h1]:text-indigo-900 [&>h1]:border-b [&>h1]:pb-2
              [&>h2]:text-2xl [&>h2]:font-semibold [&>h2]:mt-10 [&>h2]:mb-4 [&>h2]:text-indigo-800 [&>h2]:flex [&>h2]:items-center [&>h2]:gap-2
              [&>h3]:text-xl [&>h3]:font-medium [&>h3]:mt-6 [&>h3]:mb-3 [&>h3]:text-indigo-700
              [&>p]:mb-5 [&>p]:leading-relaxed [&>p]:text-gray-700
              [&>ul]:list-disc [&>ul]:ml-6 [&>ul]:mb-6 [&>ul>li]:mb-2 [&>ul>li]:text-gray-700 [&>ul>li>strong]:text-indigo-900
              [&>ol]:list-decimal [&>ol]:ml-6 [&>ol]:mb-6 [&>ol>li]:mb-2
              [&>strong]:text-indigo-900 [&>strong]:font-semibold
              [&>blockquote]:border-l-4 [&>blockquote]:border-indigo-400 [&>blockquote]:pl-5 [&>blockquote]:italic [&>blockquote]:bg-indigo-50/50 [&>blockquote]:py-3 [&>blockquote]:pr-4 [&>blockquote]:rounded-r-lg [&>blockquote]:my-6
              [&_table]:w-full [&_table]:mb-6 [&_table]:border-collapse [&_table]:border [&_table]:border-gray-200
              [&_th]:bg-indigo-50 [&_th]:border [&_th]:border-gray-200 [&_th]:px-4 [&_th]:py-2 [&_th]:text-left [&_th]:text-indigo-900
              [&_td]:border [&_td]:border-gray-200 [&_td]:px-4 [&_td]:py-2"
            >
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {result}
              </ReactMarkdown>
            </div>
          ) : (
            <div className="text-center py-16 text-gray-500">
              <span className="text-5xl block mb-4">🔍</span>
              <p className="text-xl">Please enter a disease or medical query to analyze.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function KnowledgeSearchPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Suspense fallback={<div className="p-8 text-center text-indigo-600 font-bold">Initializing AI Engine...</div>}>
        <SearchContent />
      </Suspense>
    </div>
  );
}
